### ISSUE TITLE
While running BatAlgorithm, I encounter Typeerror

### ISSUE THREAD

**Issue by SrGrace** [buma/BatAlgorithm#4]
`TypeError                                 Traceback (most recent call last)
<ipython-input-146-081e8b69f5b4> in <module>()
     15 for i in range(10):
     16     Algorithm = BatAlgorithm(10, 40, 1000, 0.5, 0.5, 0.0, 2.0, -10.0, 10.0, Fun)
---> 17     Algorithm.move_bat()

C:\Users\Sourav\mtp_codes\BatAlgorithm.py in move_bat(self)
     79                 rnd = random.random
     80 
---> 81                 if rnd > self.r:
     82                     for j in range(self.D):
     83                         S[i][j] = self.best[j] + 0.001 * random.gauss(0, 1)

TypeError: unorderable types: builtin_function_or_method() > float()`

**Comment by ujjwalkhandelwal** [comment]
Change rnd = random.random to rnd = random.random()
